### ISSUE TITLE
Fix for clang compiler instead of GCC

### ISSUE THREAD

**Issue by gilcel** [SeisComP/contrib-ipgp#1]
Here's a fix for CMakeLists.txt to allow compilation with clang instead of GCC (macOS & BSD)

```
IF(CMAKE_COMPILER_IS_GNUCC)
	IF(GCC_VERSION VERSION_LESS "4.7")
		MESSAGE(FATAL_ERROR "GCC version ${GCC_VERSION} found but 4.7 required as minimum")
	ENDIF()
ENDIF()
```

**Comment by gempa-jabe** [comment]
Thanks for the reminder, this fix has been done some time ago but forgotten to be pushed.
